<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._JPU3r_' shared service.

return $this->privates['.service_locator._JPU3r_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DepotController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DepotController::versement' => ['privates', '.service_locator..dGWmed', 'get_ServiceLocator__DGWmedService.php', true],
    'App\\Controller\\PartenaireController::list' => ['privates', '.service_locator.Vyr21Xo', 'get_ServiceLocator_Vyr21XoService.php', true],
    'App\\Controller\\PartenaireController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\PartenaireController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\PartenaireController::update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\RegistrationController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\CompteController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DepotController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DepotController:versement' => ['privates', '.service_locator..dGWmed', 'get_ServiceLocator__DGWmedService.php', true],
    'App\\Controller\\PartenaireController:list' => ['privates', '.service_locator.Vyr21Xo', 'get_ServiceLocator_Vyr21XoService.php', true],
    'App\\Controller\\PartenaireController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\PartenaireController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\PartenaireController:update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\RegistrationController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\CompteController::setViewHandler' => '?',
    'App\\Controller\\DepotController::setViewHandler' => '?',
    'App\\Controller\\DepotController::versement' => '?',
    'App\\Controller\\PartenaireController::list' => '?',
    'App\\Controller\\PartenaireController::register' => '?',
    'App\\Controller\\PartenaireController::setViewHandler' => '?',
    'App\\Controller\\PartenaireController::update' => '?',
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\RegistrationController::setViewHandler' => '?',
    'App\\Controller\\CompteController:setViewHandler' => '?',
    'App\\Controller\\DepotController:setViewHandler' => '?',
    'App\\Controller\\DepotController:versement' => '?',
    'App\\Controller\\PartenaireController:list' => '?',
    'App\\Controller\\PartenaireController:register' => '?',
    'App\\Controller\\PartenaireController:setViewHandler' => '?',
    'App\\Controller\\PartenaireController:update' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\RegistrationController:setViewHandler' => '?',
]);
