<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Od6wcbs' shared service.

return $this->privates['.service_locator.Od6wcbs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'transy' => ['privates', 'App\\Repository\\TarifRepository', 'getTarifRepositoryService.php', true],
    'user' => ['privates', '.errored..service_locator.Od6wcbs.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Od6wcbs": it references class "App\\Entity\\User" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'transy' => 'App\\Repository\\TarifRepository',
    'user' => 'App\\Entity\\User',
    'validator' => '?',
]);
