<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ruLjBfN' shared service.

return $this->privates['.service_locator.ruLjBfN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'partenaire' => ['privates', '.errored..service_locator.ruLjBfN.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.ruLjBfN": it references class "App\\Entity\\User" but no such service exists.'],
], [
    'entityManager' => '?',
    'partenaire' => 'App\\Entity\\User',
]);
