<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.H_V.0ui' shared service.

return $this->privates['.service_locator.H_V.0ui'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'repository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
    'transaction' => ['privates', '.errored..service_locator.H_V.0ui.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.H_V.0ui": it references class "App\\Entity\\Transaction" but no such service exists.'],
    'transy' => ['privates', 'App\\Repository\\TarifRepository', 'getTarifRepositoryService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'entityManager' => '?',
    'repository' => 'App\\Repository\\TransactionRepository',
    'transaction' => 'App\\Entity\\Transaction',
    'transy' => 'App\\Repository\\TarifRepository',
    'validator' => '?',
]);
