<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GgODKrk' shared service.

return $this->privates['.service_locator.GgODKrk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DepotController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DepotController::versement' => ['privates', '.service_locator..dGWmed', 'get_ServiceLocator__DGWmedService.php', true],
    'App\\Controller\\PartenaireController::ajout' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\PartenaireController::list' => ['privates', '.service_locator.Vyr21Xo', 'get_ServiceLocator_Vyr21XoService.php', true],
    'App\\Controller\\PartenaireController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\PartenaireController::update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\RegistrationController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\RegistrationController::statut' => ['privates', '.service_locator.dzuVBi3', 'get_ServiceLocator_DzuVBi3Service.php', true],
    'App\\Controller\\CompteController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DepotController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\DepotController:versement' => ['privates', '.service_locator..dGWmed', 'get_ServiceLocator__DGWmedService.php', true],
    'App\\Controller\\PartenaireController:ajout' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\PartenaireController:list' => ['privates', '.service_locator.Vyr21Xo', 'get_ServiceLocator_Vyr21XoService.php', true],
    'App\\Controller\\PartenaireController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\PartenaireController:update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\RegistrationController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\RegistrationController:statut' => ['privates', '.service_locator.dzuVBi3', 'get_ServiceLocator_DzuVBi3Service.php', true],
], [
    'App\\Controller\\CompteController::setViewHandler' => '?',
    'App\\Controller\\DepotController::setViewHandler' => '?',
    'App\\Controller\\DepotController::versement' => '?',
    'App\\Controller\\PartenaireController::ajout' => '?',
    'App\\Controller\\PartenaireController::list' => '?',
    'App\\Controller\\PartenaireController::setViewHandler' => '?',
    'App\\Controller\\PartenaireController::update' => '?',
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\RegistrationController::setViewHandler' => '?',
    'App\\Controller\\RegistrationController::statut' => '?',
    'App\\Controller\\CompteController:setViewHandler' => '?',
    'App\\Controller\\DepotController:setViewHandler' => '?',
    'App\\Controller\\DepotController:versement' => '?',
    'App\\Controller\\PartenaireController:ajout' => '?',
    'App\\Controller\\PartenaireController:list' => '?',
    'App\\Controller\\PartenaireController:setViewHandler' => '?',
    'App\\Controller\\PartenaireController:update' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\RegistrationController:setViewHandler' => '?',
    'App\\Controller\\RegistrationController:statut' => '?',
]);
