<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.sWs_Lgq' shared service.

return $this->privates['.service_locator.sWs_Lgq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'transaction' => ['privates', '.errored..service_locator.sWs_Lgq.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.sWs_Lgq": it references class "App\\Entity\\Transaction" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'entityManager' => '?',
    'transaction' => 'App\\Entity\\Transaction',
    'validator' => '?',
]);
