<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQQj9ukn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQQj9ukn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQQj9ukn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQQj9ukn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQQj9ukn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QQj9ukn',
    'container.build_id' => '32484350',
    'container.build_time' => 1565979516,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQQj9ukn');
