<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKD4xcRr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKD4xcRr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKD4xcRr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKD4xcRr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKD4xcRr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KD4xcRr',
    'container.build_id' => 'a63713fb',
    'container.build_time' => 1567541989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKD4xcRr');
