<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLQKhszo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLQKhszo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLQKhszo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLQKhszo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLQKhszo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LQKhszo',
    'container.build_id' => '7cef0138',
    'container.build_time' => 1568131891,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLQKhszo');
